references:
  defaults: &defaults
    working_directory: ~/theme
    docker:
      - image: circleci/php:7.2-stretch-node-browsers-legacy
    
  npm_permissions: &npm_permissions
    run:
      name: Set user permissions
      command: sudo chown -R $(whoami):$(whoami) ~/theme

  npm_install: &npm_install
    run:
      name: Install NPM packages
      command: npm install --silent
  
  gulp_build_staging: &gulp_build_staging
    run:
      name: Gulp build staging
      command: npx gulp build
  
  gulp_build_production: &gulp_build_production
    run:
      name: Gulp build production
      command: npx gulp buildProd
  
  composer_install: &composer_install
    run:
      name: Compile vendors from composer packages
      command: composer install -n --ignore-platform-reqs --optimize-autoloader
  
  append_sshkey: &append_sshkey
    add_ssh_keys:
      fingerprints:
        - "48:25:12:66:70:3c:53:fc:e2:a2:4b:39:55:6c:a3:46"
  
  add_serverkeys: &add_serverkeys
    run:
      name: Add server keys
      command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  
  deploy_staging: &deploy_staging
    run:
      name: Rsync deploy to staging
      command:  rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . root@$SERVER_IP:$STAGING_PATH

  deploy_production: &deploy_production
    run:
      name: Rsync deploy to production
      command: rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . root@$SERVER_IP:$PRODUCTION_PATH

version: 2
jobs:
  jslint:
    <<: *defaults
    steps:
      - checkout
      - << : *npm_permissions
      - << : *npm_install
      - run: npx gulp jsLint

  sasslint:
    <<: *defaults
    steps:
      - checkout
      - << : *npm_permissions
      - << : *npm_install
      - run: npx gulp sassLint

  staging:
    <<: *defaults
    steps:
      - checkout
      - << : *npm_permissions
      - << : *npm_install
      - << : *composer_install
      - << : *gulp_build_staging
      - << : *append_sshkey
      - << : *add_serverkeys
      - << : *deploy_staging

  production:
    <<: *defaults
    steps:
      - checkout
      - << : *npm_permissions
      - << : *npm_install
      - << : *composer_install
      - << : *gulp_build_production
      - << : *append_sshkey
      - << : *add_serverkeys
      - << : *deploy_production

workflows: 
  version: 2
  deploy:
    jobs:
      - jslint:
          filters: &filter_all
            tags:
              only: /.*?/

      - sasslint:
          filters: *filter_all

      - staging:
          requires:
            - jslint
            - sasslint
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                # v1.0.0-1 / v1.0.0-pre1 / v1.0.0
                - /^v\d+\.\d+\.\d+(\-.+)?$/
      
      - approve_deploy:
          type: approval
          requires:
            - staging
          filters: &filter_production
            branches:
              ignore: /.*/
            tags:
              only:
                # v1.0.0
                - /^v\d+\.\d+\.\d+$/
      
      - production: 
          requires: 
            - staging
            - approve_deploy
          filters: *filter_production